[build]
target = "avr-none"
rustflags = ["-C", "target-cpu=atmega2560"]

[target.'cfg(target_arch = "avr")']
runner = "ravedude"

[unstable]
build-std = ["core"]

[env]
CC_avr_none = "avr-gcc"
CXX_avr_none = "avr-g++"
AR_avr_none = "avr-ar"